### ISSUE TITLE
`nrm help` throws error

### ISSUE THREAD

**Issue by nswbmw** [Pana/nrm#23]
nrm :v1.0.0

```
/usr/local/lib/node_modules/nrm/node_modules/commander/index.js:1023
  process.stdout.write(cb(this.helpInformation()));
                       ^

TypeError: cb is not a function
  at Command.outputHelp (/usr/local/lib/node_modules/nrm/node_modules/commander/index.js:1023:24)
  at Command.help (/usr/local/lib/node_modules/nrm/node_modules/commander/index.js:1034:8)
  at Command.listener (/usr/local/lib/node_modules/nrm/node_modules/commander/index.js:301:8)
  at emitTwo (events.js:87:13)
  at Command.emit (events.js:172:7)
  at Command.parseArgs (/usr/local/lib/node_modules/nrm/node_modules/commander/index.js:615:12)
  at Command.parse (/usr/local/lib/node_modules/nrm/node_modules/commander/index.js:458:21)
  at Object.<anonymous> (/usr/local/lib/node_modules/nrm/cli.js:63:6)
  at Module._compile (module.js:409:26)
  at Object.Module._extensions..js (module.js:416:10)
  at Module.load (module.js:343:32)
  at Function.Module._load (module.js:300:12)
  at Function.Module.runMain (module.js:441:10)
  at startup (node.js:139:18)
  at node.js:974:3
```

**Comment by yuxingxin** [comment]
可以使用`nrm -h`  或者 `nrm  --help`

**Comment by Pana** [comment]
thanks for report, it has been fixed !
