### ISSUE TITLE
安装成功但无法使用

### ISSUE THREAD

**Issue by liangyuanzu** [Pana/nrm#82]
node version v14.15.4
npm version 6.14.10
nrm version 1.2.1

报错信息：
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

[TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
  at validateString (internal/validators.js:124:11)
  at Object.join (path.js:375:7)
  at Object.<anonymous> (D:\Dev\NVM\v14.15.4\node_modules\nrm\cli.js:17:20)
  at Module._compile (internal/modules/cjs/loader.js:1063:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Module.load (internal/modules/cjs/loader.js:928:32)
  at Function.Module._load (internal/modules/cjs/loader.js:769:14)
  at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
  at internal/main/run_main_module.js:17:47
] {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by Megalovania-ding** [comment]
move: #79 [fix](https://github.com/stefango/nrm/commit/f5027595adeedb186c47bae1729e6a11d30927db)

**Comment by mousne** [comment]
node version 12.20.1
npm version 7.5.2

still error
