### ISSUE TITLE
Not support node 8.x

### ISSUE THREAD

**Issue by goldcome** [Pana/nrm#86]
install success, but not work
```
nrm use taobao

/home/worker/.nvm/versions/node/v8.17.0/lib/node_modules/nrm/node_modules/open/index.js:38
                } catch {}
                        ^

SyntaxError: Unexpected token {
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:139:10)
  at Module._compile (module.js:617:28)
  at Object.Module._extensions..js (module.js:664:10)
  at Module.load (/home/worker/.nvm/versions/node/v8.17.0/lib/node_modules/nrm/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at tryModuleLoad (module.js:506:12)
  at Function.Module._load (module.js:498:3)
  at Module.require (module.js:597:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/home/worker/.nvm/versions/node/v8.17.0/lib/node_modules/nrm/cli.js:10:14)
  at Module._compile (module.js:653:30)
```

**Comment by goldcome** [comment]
switch version 1.0.2 working! close it
